# HybridRAG Configuration File

# Database Configuration
database:
  neo4j:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "password"
    database: "neo4j"

# Retrieval Configuration
retrieval:
  default_top_k: 5
  vector_similarity_threshold: 0.7
  strategy_weights:
    vector: 0.4
    fulltext: 0.3
    semantic: 0.3

# Embedding Configuration
embeddings:
  model: "text-embedding-ada-002"
  dimension: 1536
  batch_size: 100

# LLM Configuration
llm:
  max_context_length: 4000
  temperature: 0.7
  max_tokens: 500

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null  # Set to file path if you want file logging

# Index Configuration
indexes:
  vector:
    name: "documentEmbeddingIndex"
    label: "Document"
    property: "embedding"
    dimension: 1536
  fulltext:
    name: "documentFulltextIndex"
    label: "Document"
    properties: ["text"]
